version: '3.8'

services:
  email-capture:
    build: .
    volumes:
      - ./emails_data:/app/emails_data
    environment:
      - PORT=3000
      - VIRTUAL_HOST=codingtree.org
      - LETSENCRYPT_HOST=codingtree.org
      - LETSENCRYPT_EMAIL=elianrenteriadevelopment@gmail.com
    networks:
      - proxy

networks:
  proxy:
    external: true